baseURL = "https://scraly.github.io/"
languageCode = "en-us"
title = "Scraly tech blog"
theme = "hemingway"
enableEmoji = true
copyright = "&copy; <a href=\"http://scraly.com\">Aurélie Vache</a> 2018"
googleAnalytics = "UA-118651176-1"

# Pagination
paginate = 10
paginatePath = "page"

staticDir = "static"

[taxonomies]
  tag = "tags"
  category = "categories"

# Links format

[permalinks]
post = "/:year/:month/:title/"

[params]
  # Main sections (currently used for the recent posts in the sidebar)
  mainSections = ["post"]

  # Default author
  author = "Aurélie Vache"

  site_name = "Scraly/Aurélie Vache tech blog"
  description = "" 

  # tagline = "the tagline for this website"

  [params.highlight]
  style = "github"
  languages = ["go", "dockerfile"]

  [[params.social]]
  url = "https://github.com/scraly"
  fa_icon = "fa-github"

  [[params.social]]
  url = "https://twitter.com/aurelievache"
  fa_icon = "fa-twitter"

  [[params.social]]
  url = "https://www.linkedin.com/in/aurelievache/"
  fa_icon = "fa-linkedin"

  [[params.social]]
  url = "https://scraly.com"
  fa_icon = "fa-globe"

[author]
    name = "Aurélie Vache"       #Author name
    github = "scraly"     #Github username
    twitter = "aurelievache"    #Twitter username
    #linkedin = ""   #LinkedIn username

# pygmentsCodeFences = true
# pygmentsUseClasses = true
